# Generated by Django 5.0.7 on 2024-07-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=255)),
                ('descricao', models.TextField()),
                ('dispositivos', models.CharField(max_length=255)),
                ('imagem_url', models.URLField(blank=True, null=True)),
                ('faq', models.JSONField(default=dict)),
                ('relacionados', models.ManyToManyField(blank=True, related_name='relacionado a', to='core.software')),
            ],
        ),
    ]
