# Generated by Django 5.0.7 on 2024-07-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='nome',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
