# Generated by Django 5.0.8 on 2024-08-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_software_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pergunta', models.TextField(default='')),
                ('resposta', models.TextField(default='')),
            ],
        ),
    ]
